### ISSUE TITLE
Use a React app in more than one page

### ISSUE THREAD

**Issue by rockiger** [rockiger/reactpress#12]
As a website maintainer, I want the React app I created in several places in my WP site, that I don't repeat myself.

- [x] Change model in the options
- [x] Create an update path
- [x] Create the possibility to add more pages to an app in the GUI
- [x] Let the user add an app to existing pages

**Comment by MauriceMorrey** [comment]
Possible solution? See end of article.

https://javascript.plainenglish.io/how-to-add-a-react-app-to-wordpress-pages-61aee723d607

**Comment by rockiger** [comment]
I couldn't find anything that would help.

The approach in the article is to use WordPress's React installation, which it uses for Gutenberg and full-site editing. I can't think of a way I would hate more to develop React apps. Sorry, for being that harsh.

I think the implementation should be pretty straight forward, if I find the time or somebody else is pitching in.

We probably only need to make it possible to set more page slugs for a certain appname. The code at the moment does that:
```
add_option('repr_apps', [[
				'appname' => $appname,
				'pageslug' => $pageslug,
			]]);
```

One solution would be to create 'more' apps or add a list of slugs. But the first approach seems more backwards compatible.
