### ISSUE TITLE
error on React Press plugin page

### ISSUE THREAD

**Issue by thanosSidi** [rockiger/reactpress#13]
When i activate the Plugin i get this error
Warning: foreach() argument must be of type array|object, bool given in C:\xampp\htdocs\ReactWordpress\wp-content\plugins\reactpress-main\public\class-reactpress-public.php on line 201

Furthermore, when i select the React Press from the wordpress admin menu bar the following error is displaying of the options on the video

Fatal error: Uncaught TypeError: array_map(): Argument #2 ($array) must be of type array, bool given in C:\xampp\htdocs\ReactWordpress\wp-content\plugins\reactpress-main\admin\class-reactpress-admin.php:725 Stack trace: #0 C:\xampp\htdocs\ReactWordpress\wp-content\plugins\reactpress-main\admin\class-reactpress-admin.php(725): array_map(Object(Closure), false) #1 C:\xampp\htdocs\ReactWordpress\wp-content\plugins\reactpress-main\admin\partials\reactpress-admin-display.php(19): Reactpress_Admin->get_apps() #2 C:\xampp\htdocs\ReactWordpress\wp-content\plugins\reactpress-main\admin\class-reactpress-admin.php(106): require_once('C:\\xampp\\htdocs...') #3 C:\xampp\htdocs\ReactWordpress\wp-includes\class-wp-hook.php(303): Reactpress_Admin->{closure}('') #4 C:\xampp\htdocs\ReactWordpress\wp-includes\class-wp-hook.php(327): WP_Hook->apply_filters('', Array) #5 C:\xampp\htdocs\ReactWordpress\wp-includes\plugin.php(470): WP_Hook->do_action(Array) #6 C:\xampp\htdocs\ReactWordpress\wp-admin\admin.php(259): do_action('toplevel_page_r...') #7 {main} thrown in C:\xampp\htdocs\ReactWordpress\wp-content\plugins\reactpress-main\admin\class-reactpress-admin.php on line 725

**Comment by rockiger** [comment]
Thanks, fixed it.
