### ISSUE TITLE
documentation, closing down or alternative to shell_exec, exec

### ISSUE THREAD

**Issue by wibed** [rockiger/reactpress#22]
is there documentation on alternative approach to shell_exec, exec

ex.: 
a limited set of necessary commands available, to a user which is running as the php 
user. 

maybe one of you has already done that

EDIT:
a example for production, would be great

**Comment by rockiger** [comment]
You don't need `shell_exec` anymore. Which version of the plugin do you use?

The apps directory is created by [`wp_mkdir_p`](https://developer.wordpress.org/reference/functions/wp_mkdir_p/). It uses the php function `mkdir`. This needs to be available.

Could you post your system configuration (OS, environment, etc) and debug with [WP Debugging](https://wordpress.org/plugins/wp-debugging/) to look for errors?

**Comment by wibed** [comment]
its a debian, but dont have a root user available.
it does not create the directory `apps`, nor am i able to run `npx install` afterwards.
so i assume it does not work and its because of permissions.

do i need root privileges?

**Comment by rockiger** [comment]
Sounds to me that you need a working dev environment. If you can't run `npx create-react-app`, you can't use the plugin. 

Are we talking about a dev environment or a live server?
