### ISSUE TITLE
Blank admin page

### ISSUE THREAD

**Issue by pyleglise** [rockiger/reactpress#29]
Hello 

I just installed ReactPress on my wordpress server (Linux) but when I click on ReactPress, in the left main menu, I just have a blank page...

Best regards, 
PY

**Comment by rockiger** [comment]
This is very odd. Could you please post your environment, your browser console output, your theme and maybe a screenshot?

I tested it with a fresh install on LocalWP and I can see the admin interface of ReactPress.

**Comment by pyleglise** [comment]
Hi,
Here's the screen shot with console (no error) :
![image](https://user-images.githubusercontent.com/101606260/204625908-c50b8dfe-5d09-450f-9a70-4b27f9818df1.png)

Here's the environnement :
![image](https://user-images.githubusercontent.com/101606260/204626724-1800392a-58e2-422c-b222-c3e185de2ff9.png)

Theme used (i don't think it's revelent as the problem is on the admin part) :
![image](https://user-images.githubusercontent.com/101606260/204627915-23a9381a-04b1-45fe-9b50-e9f2c84f64db.png)

Fully detailled console log after click on admin ReactPress :
15:24:20,353 Ouverture de https://www.axialdata.net/wp-admin/admin.php?page=reactpress
15:24:20,399
GEThttps://www.axialdata.net/wp-admin/admin.php?page=reactpress
[HTTP/2 200 OK 1820ms]

15:24:22,250 Cette page utilise la propriété non standard « zoom ». Envisagez d’utiliser calc() dans les valeurs des propriétés pertinentes ou utilisez « transform » avec « transform-origin: 0 0 ». [admin.php](https://www.axialdata.net/wp-admin/admin.php?page=reactpress)
15:24:22,388
GEThttps://www.axialdata.net/wp-includes/js/jquery/jquery.min.js?ver=3.6.1
[HTTP/2 200 OK 0ms]

15:24:22,389
GEThttps://www.axialdata.net/wp-includes/js/jquery/jquery-migrate.min.js?ver=3.3.2
[HTTP/2 200 OK 0ms]

15:24:22,390
GEThttps://www.axialdata.net/wp-includes/js/utils.min.js?ver=6.1.1
[HTTP/2 200 OK 0ms]

15:24:22,391
GEThttps://www.axialdata.net/wp-content/plugins/wp-optimize//includes/blockui/jquery.blockUI.min.js?ver=3.2.9
[HTTP/2 200 OK 0ms]

15:24:22,393
GEThttps://www.axialdata.net/wp-content/plugins/wp-optimize/js/send-command-3-2-9.min.js?ver=3.2.9
[HTTP/2 200 OK 0ms]

15:24:22,394
GEThttps://www.axialdata.net/wp-content/plugins/wp-optimize/js/wposmush-3-2-9.min.js?ver=3.2.9
[HTTP/2 200 OK 0ms]

15:24:22,396
GEThttps://www.axialdata.net/wp-content/plugins/alt-manager/assets/js/jquery.switcher.min.js?ver=6.1.1
[HTTP/2 200 OK 0ms]

15:24:22,397
GEThttps://www.axialdata.net/wp-content/plugins/alt-manager/assets/js/select2.min.js?ver=6.1.1
[HTTP/2 200 OK 0ms]

15:24:22,398
GEThttps://www.axialdata.net/wp-content/plugins/alt-manager/assets/js/alm-admin-script.js?ver=6.1.1
[HTTP/2 200 OK 0ms]

15:24:22,403
GEThttps://www.axialdata.net/wp-content/plugins/ultimate-social-media-icons/analyst/assets/js/customize.js?ver=6.1.1
[HTTP/2 200 OK 0ms]

15:24:22,405
GEThttps://www.axialdata.net/wp-content/plugins/easy-table-of-contents/includes/feedback.js?ver=6.1.1
[HTTP/2 200 OK 0ms]

15:24:22,406
GEThttps://www.axialdata.net/wp-content/plugins/updraftplus/central/js/central.js?ver=1.22.23
[HTTP/2 200 OK 0ms]

15:24:22,409
GEThttps://platform.linkedin.com/in.js
[HTTP/2 200 OK 0ms]

15:24:22,411
GEThttps://www.axialdata.net/wp-includes/js/hoverIntent.min.js?ver=1.10.2
[HTTP/2 200 OK 0ms]

15:24:22,412
GEThttps://www.axialdata.net/wp-includes/js/dist/vendor/regenerator-runtime.min.js?ver=0.13.9
[HTTP/2 200 OK 0ms]

15:24:22,413
GEThttps://www.axialdata.net/wp-includes/js/dist/hooks.min.js?ver=4169d3cf8e8d95a3d6d5
[HTTP/2 200 OK 0ms]

15:24:22,413
GEThttps://www.axialdata.net/wp-includes/js/dist/vendor/wp-polyfill.min.js?ver=3.15.0
[HTTP/2 200 OK 0ms]

15:24:22,414
GEThttps://www.axialdata.net/wp-includes/js/dist/i18n.min.js?ver=9e794f35a71bb98672ae
[HTTP/2 200 OK 0ms]

15:24:22,415
GEThttps://www.axialdata.net/wp-admin/js/common.min.js?ver=6.1.1
[HTTP/2 200 OK 0ms]

15:24:22,416
GEThttps://www.axialdata.net/wp-includes/js/admin-bar.min.js?ver=6.1.1
[HTTP/2 200 OK 0ms]

15:24:22,416
GEThttps://www.axialdata.net/wp-includes/js/hoverintent-js.min.js?ver=2.2.1
[HTTP/2 200 OK 0ms]

15:24:22,417
GEThttps://www.axialdata.net/wp-includes/js/jquery/ui/core.min.js?ver=1.13.2
[HTTP/2 200 OK 0ms]

15:24:22,418
GEThttps://www.axialdata.net/wp-includes/js/jquery/ui/mouse.min.js?ver=1.13.2
[HTTP/2 200 OK 0ms]

15:24:22,419
GEThttps://www.axialdata.net/wp-includes/js/jquery/ui/draggable.min.js?ver=1.13.2
[HTTP/2 200 OK 0ms]

15:24:22,421
GEThttps://www.axialdata.net/wp-includes/js/jquery/ui/slider.min.js?ver=1.13.2
[HTTP/2 200 OK 0ms]

15:24:22,422
GEThttps://www.axialdata.net/wp-includes/js/jquery/jquery.ui.touch-punch.js?ver=0.2.2
[HTTP/2 200 OK 0ms]

15:24:22,423
GEThttps://www.axialdata.net/wp-admin/js/iris.min.js?ver=1.1.1
[HTTP/2 200 OK 0ms]

15:24:22,424
GEThttps://www.axialdata.net/wp-admin/js/color-picker.min.js?ver=6.1.1
[HTTP/2 200 OK 0ms]

15:24:22,426
GEThttps://www.axialdata.net/wp-content/plugins/easy-table-of-contents/assets/js/admin.js?ver=2.0.38
[HTTP/2 200 OK 0ms]

15:24:22,427
GEThttps://www.axialdata.net/wp-admin/js/svg-painter.js?ver=6.1.1
[HTTP/2 200 OK 0ms]

15:24:22,428
GEThttps://www.axialdata.net/wp-includes/js/heartbeat.min.js?ver=6.1.1
[HTTP/2 200 OK 0ms]

15:24:22,428
GEThttps://www.axialdata.net/wp-content/plugins/reactpress/admin/js/reactpress-admin.js?ver=2.1.2
15:24:22,430
GEThttps://www.axialdata.net/wp-includes/js/wp-auth-check.min.js?ver=6.1.1
[HTTP/2 200 OK 0ms]

15:24:22,431
GEThttps://www.axialdata.net/wp-content/plugins/email-encoder-bundle/core/includes/assets/js/encoder-form.js?ver=220816-115554
[HTTP/2 200 OK 0ms]

15:24:22,432
GEThttps://www.axialdata.net/wp-content/plugins/matomo/assets/js/admin.js?ver=1.0
[HTTP/2 200 OK 0ms]

15:24:22,434
GEThttps://www.axialdata.net/wp-content/plugins/ultimate-social-media-icons/wpses/wpse1_6817_notiad.min.js?ver=6.1.1
[HTTP/2 200 OK 0ms]

15:24:22,435
GEThttps://www.axialdata.net/wp-content/themes/gradiant/assets/js/gradiant-admin-script.js?ver=6.1.1
[HTTP/2 200 OK 0ms]

15:24:22,436
GEThttps://www.axialdata.net/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-i18n-e29c32171c9d96a19747.js
[HTTP/2 200 OK 0ms]

15:24:22,437
GEThttps://www.axialdata.net/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-base-a3526c4840a94640920f.js
[HTTP/2 200 OK 0ms]

15:24:22,438
GEThttps://www.axialdata.net/wp-content/plugins/seo-by-rank-math/vendor/cmb2/cmb2/js/cmb2.min.js?ver=2.10.1
[HTTP/2 200 OK 0ms]

15:24:22,438
GEThttps://www.axialdata.net/wp-includes/js/jquery/ui/sortable.min.js?ver=1.13.2
[HTTP/2 200 OK 0ms]

15:24:22,456 JQMIGRATE: Migrate is installed, version 3.3.2 [jquery-migrate.min.js:2:709](https://www.axialdata.net/wp-includes/js/jquery/jquery-migrate.min.js?ver=3.3.2)
15:24:22,548
GEThttps://www.axialdata.net/wp-includes/js/wp-emoji-release.min.js?ver=6.1.1
[HTTP/2 200 OK 0ms]

15:24:22,646
GEThttps://connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.5
[HTTP/3 200 OK 0ms]

15:24:22,667
GEThttps://connect.facebook.net/fr_FR/sdk.js?hash=e2cac4d2d166a99938bb8fa3eedee459
[HTTP/3 200 OK 0ms]

15:24:22,668
GEThttps://www.axialdata.net/wp-content/uploads/2022/07/cropped-Logo-carre-AxialData-v2-192x192.png
[HTTP/2 200 OK 0ms]

15:24:22,670
GEThttps://www.axialdata.net/wp-content/uploads/2022/07/cropped-Logo-carre-AxialData-v2-32x32.png
[HTTP/2 200 OK 0ms]

15:24:22,732
Erreur d’analyse de la valeur pour « background ».  Déclaration abandonnée. [admin.php:3:2284](https://www.axialdata.net/wp-admin/admin.php?page=reactpress)
15:24:22,732
Erreur d’analyse de la valeur pour « background ».  Déclaration abandonnée. [admin.php:3:2910](https://www.axialdata.net/wp-admin/admin.php?page=reactpress)
15:24:22,732 Règle keyframe ignorée suite à un mauvais sélecteur. [admin.php:5:1462](https://www.axialdata.net/wp-admin/admin.php?page=reactpress)
15:24:22,732 Règle keyframe ignorée suite à un mauvais sélecteur. [admin.php:5:1616](https://www.axialdata.net/wp-admin/admin.php?page=reactpress)
15:24:22,764
GEThttps://cdnsure.com/assets/alert
15:24:22,784 Cette page est en mode de compatibilité (quirks). La mise en page peut en être affectée. Pour le mode standard, utilisez « <!DOCTYPE html> ».
[alert](https://cdnsure.com/assets/alert)
15:24:22,806
Propriété « alignment-baseline » inconnue.  Déclaration abandonnée. [alert:33:24](https://cdnsure.com/assets/alert)
15:24:22,806
Propriété « alignment-baseline » inconnue.  Déclaration abandonnée. [alert:67:24](https://cdnsure.com/assets/alert)

​Let me know if you need anything else.

**Comment by rockiger** [comment]
This is very strange. For whatever reason, `https://www.axialdata.net/wp-content/plugins/reactpress/admin/js/reactpress-admin.js?ver=2.1.2` doesn't load the React app. ReactPress admin is a React app itself.

I have no plausible idea. Maybe deleting the plugin and installing it again?

**Comment by pyleglise** [comment]
I already tried that.
I'll try to remove others extensions one by one... See if it's some other stuff that puts mess...
I'll let you know.

**Comment by pyleglise** [comment]
Waow !!
I just deactivated ALL the plugins (except ReactPress) from my WP.
I switched to the basic theme  : twenty twenty one
And I still have the same problem...
This is weird...

**Comment by rockiger** [comment]
Totally strange. Has the script I posted above any content? There should be some error message.

**Comment by pyleglise** [comment]
Here's what I have with the url : https://www.axialdata.net/wp-content/plugins/reactpress/admin/js/reactpress-admin.js?ver=2.1.2
![image](https://user-images.githubusercontent.com/101606260/205332827-2d84c98c-a643-4664-893b-a952c6b5b3e1.png)

**Comment by pyleglise** [comment]
And the source code received is completely empty. Not even a "<DOC!"

**Comment by EcBen** [comment]
@rockiger Seeing this same issue on version 2.1.2. Have another site on 2.1.1 and it's loading fine.
Where's the source code for versions greater than 2.0.1? This repo hasn't been updated in 2 months.

**Comment by EcBen** [comment]
I tried downgrading to 2.1.1 and it didn't help.

**Comment by EcBen** [comment]
I was able to fix the error. Was seeing this in the debug.log:
```
PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/myuser/wp-content/plugins/reactpress/admin/Admin.php on line 106
PHP Warning:  file_get_contents(https://example.com/wp-content/plugins/reactpress/admin/js/reactpress-admin/build/asset-manifest.json): failed to open stream: no suitable wrapper could be found in /home/myuser/wp-content/plugins/reactpress/admin/Admin.php on line 106
```

Edit the `php.ini` file:
```
allow_url_fopen = On
```

Then restart the `php-fpm` service:
```
sudo systemctl restart php7.4-fpm.service
```

**Comment by pyleglise** [comment]
Unfortunately, I don't have access to the server administration...

**Comment by rockiger** [comment]
> @rockiger Seeing this same issue on version 2.1.2. Have another site on 2.1.1 and it's loading fine. Where's the source code for versions greater than 2.0.1? This repo hasn't been updated in 2 months.

Sorry, I only released to SVN. My bad. Source code is pushed.

**Comment by rockiger** [comment]
Do you guys know any alternative to `fopen`. Without the `manifest.json` ReactPress doesn't know, which javascript files to load.

I should definitely catch that error and tell the user about it.

**Comment by VicMed28** [comment]
I have the same issue. Installed both locally and live reactPress, locally works fine, but on live appears a blank screen.

**Comment by rockiger** [comment]
Your live host must allow `fopen` otherwise it won't work

**Comment by rockiger** [comment]
I have thought about a solution. We could add a text area in the admin. Where a user could add the content of the `asset-manifest.json`.

Would that help you with your problems?

**Comment by rockiger** [comment]
Hey guys,

I think I fixed the problem. This should now work on all hosts.

Could you check if the pre-release works for you: [ReactPress-3.0.0-pre.zip](https://drive.google.com/file/d/1A6UgbZDYnTEkL1gpg9fu8QbQZh8_WWuJ/view?usp=sharing)?

Thanks.
