### ISSUE TITLE
Support Vite

### ISSUE THREAD

**Issue by rockiger** [rockiger/reactpress#32]
- [x] Images on dev-server
- [x] Images in build
- [x] ReactPress canvas
- [x] Support JS-files on dev-server
- [x] Test with Fulcrum

**Comment by Solomon04** [comment]
how's this coming along?

**Comment by rockiger** [comment]
@Solomon04 This will be in the release after the next one. I don't have any clear timeline, I would assume within the next 4 weeks.

Vite works different from CRA, so I have to look into it more closely.
