### ISSUE TITLE
Plugin seems to have broken the current theme

### ISSUE THREAD

**Issue by wlaurance** [rockiger/reactpress#35]
<img width="963" alt="image" src="https://user-images.githubusercontent.com/1059214/212444756-e8dd1b8e-90d4-4ff4-9403-c18c08879211.png">

Perhaps I did something incorrect but I followed the instructions and got a broken theme.

I was able to switch to a different theme and that one was able to work.

**Comment by wlaurance** [comment]
I believe I opened this in mistake. I had done a WP upgrade around the same time and it left the theme is a strange spot.

**Comment by rockiger** [comment]
No problem, I thought so. ReactPress is not dealing with the theme in any way.
