### ISSUE TITLE
Update Dev-Enviorments creates a blank page

### ISSUE THREAD

**Issue by itay-sho** [rockiger/reactpress#40]
no indication on logs, but creates a blank page.
if anyone have any leads I'll be grateful. can also provide more debugging details if required

UPDATE:
after some investigation this is what I understand:
I have two docker-compose configs.

one with localhost that works well
but when I switch it to a more advanced one like blog-local (still local production) or localhost:8090 it returns an empty index.html file

**Comment by rockiger** [comment]
Does the permalink in the ReactPress admin work? ReactPress uses `wp_remote_get` to read the host page to create a similar looking `index.html`.

I use LocalWP for development and it works fine with urls like "blog.local". Unfortunately, I don't have any knowledge with docker.

**Comment by itay-sho** [comment]
Thanks for the hint, I figured it out:
I tried to give the wordpress only internal network access, but since it tried to use wp_remote_get it failed to fetch itself, since blog-local was external network to the conatiner.

in order to solve it I just added the following to my docker compose:
```
extra_hosts:
      - "blog-local:127.0.0.1"
```

**Comment by itay-sho** [comment]
another thought about it - similar to #39 maybe the case where update cannot fetch the website should be more indicative and warn you instead of signaling a success

I am not too familiar with php but can try to send a pr for those two you want.
