### ISSUE TITLE
Path structure issues

### ISSUE THREAD

**Issue by dylanlawrence** [rockiger/reactpress#49]
I'm using an environment that has a custom directory structure, so when it comes to content path it requires the correct wp call for the specific directory. 

My main issue is shows up in the app_path method,  
which I'm able to solve with WP_CONTENT_DIR like so: 
```
$apppath = escapeshellcmd(REPR_APPS_PATH . "/{$appname}");
   // $document_root = rtrim(ABSPATH,  '/') ?? '';
if ($relative_to_home_path) {
  return explode(WP_CONTENT_DIR, $apppath)[1];
```

I'm also seeing several other similar issues,  that can be easily corrected by prefixing with - `content_url()`  before asset files

example   - _/plugins/reactpress/public/User.php:247_
`wp_enqueue_script('rp-react-app-asset-' . $app_index . '-' . $index,`  **content_url()** `. $js_file, array(), '1', true);`

then also the admin react form for Target Pages > Edit  needs a base `admin_url()`  / `wp-admin.php` ;
example :
   `echo wp_json_encode(['status' => 1, 'admin_url' => admin_url(), 'apps' => $apps]);`
   then you would need to build this in your app with the ${admin_url}/edit link path etc.

**Comment by rockiger** [comment]
Unfortunatley that doesn't work in my test environment. REPR_APPS_PATH is based WP_CONTENT_DIR.

Could you share your configuration? I don't know much about custom folder configurations in WordPress, except that they exist.

**Comment by dylanlawrence** [comment]
I just use https://roots.io/bedrock/ for WordPress projects.  It just moves
some directories to a more sensible app structure and creates a config with
multiple environments.

**Comment by rockiger** [comment]
Ok, thanks. I will try to find a solution for Bedrock that doesn't collide with the default structure (at least with my LocalWP installation).

Do I understand this correctly: You did create a workaround for yourself to ReactPress and can wait to until the next release for any fixing this issue?

**Comment by dylanlawrence** [comment]
Yes WP_CONTENT_DIR and WP_CONTENT_URL seems to work as prefix.

 - I have this in  /plugins/reactpress/public/User.php and things load without "/wp" dir getting in the middle. 
wp_enqueue_style('rp-react-app-asset-' . $app_index . '-' . $index, WP_CONTENT_URL . $css_file);
wp_enqueue_script('rp-react-app-asset-' . $app_index . '-' . $index, WP_CONTENT_URL . $js_file, array(), '1', true);

I have another issue though where I have to remove & re-add the Target Page after it breaks during the "Update Dev-Environment".   I think it's related to the same path issue, but I can't figure out why.

**Comment by rockiger** [comment]
I created a pull request with changes regarding the loading of the css- and js-assets. It works on my local Bedrock installation. Do you care to give it a try? 

[Feature/path structure issues #49](https://github.com/rockiger/reactpress/pull/51)

**Comment by dylanlawrence** [comment]
I'm getting 

PHP Fatal error:  Uncaught Error: Class "ReactPress\Includes\Core" not found /app/plugins/reactpress/reactpress.php:94.  

Everything is there - Includes/Core.php etc.

**Comment by dylanlawrence** [comment]
This looks good,  the only thing I see now is the "Edit" on the Admin App,
I was having issues with PR for this branch,  maybe a patch -
[adminAppEdit.patch](https://github.com/rockiger/reactpress/files/14353954/adminAppEdit.patch)

**Comment by rockiger** [comment]
Great, I applied the patch. It works great.

I will wait a few days until I create a new release. Another user had a [similar problem](https://github.com/rockiger/reactpress/issues/46) (that is why I use `ABSPATH` constant) and want to give him the chance to test and provide feedback on our solution.

I hope this fine with you?
