### ISSUE TITLE
Unable to update index.html for private page

### ISSUE THREAD

**Issue by BlairCooper** [rockiger/reactpress#52]
If the page used for the React app is marked as "Private", attempting to update the index.html file will say it succeeded but actually did not.

When a page is Private the get_index_html_content() function ends up retrieving the "404, Not Found" page which the function then attempts to update. This results in the index.html being replaced with the "Not Found" page which does not contain a reference to the React app.

The get_index_html_content() function should check for an OK/200 response before attempting to update the page. Further, in order to support doing an update for private pages, it should pass the cookies from the current request so that WordPress can authenticate the request for the private page.

**Comment by rockiger** [comment]
I would not have guessed that this is a use case because you can always "un-privatise" the page in your dev environment.

 Thank you for the pull request. It looks good. I will check it out, as soon as I have time.

**Comment by BlairCooper** [comment]
True, in my case the dev environment is a synced copy of production.

**Comment by rockiger** [comment]
Fair enough. That makes probably a lot of sense. How do you keep the environments in sync, if I may ask.

**Comment by BlairCooper** [comment]
I have to manually sync them but that just involves using WinSCP or rsync to sync a local directory with whats on the server. Then  MySQLDump/MySQL to dump the remote and load it into a local server. Then I use wp-cli to search and replace the actual.domain with test.actual.domain. Then another search and replace to replace https://test.actual.dom with http://test.actual.domain. Finally I have test.actual.domain point to my dev machine. Most of the time this is done via a Pi-Hole server but when travelling I use the machine's hosts file. I have two scripts/batch files do to this syncFiles.sh/.bat and reloadDatabase.sh/.bat. (I run both Windows and Ubuntu depending on what I'm doing).
